FROM docker.io/library/caddy:2-alpine@sha256:d8542f48d34a9cf4e4c11a478865229840e87e4c96ea3f439101f31a5d35f75f AS base

EXPOSE 8080

RUN mkdir -p /srv/cloud-init
COPY ./data /srv/cloud-init
COPY ./Caddyfile /etc/caddy/Caddyfile
