FROM docker.io/library/caddy:2-alpine@sha256:5f5c8640aae01df9654968d946d8f1a56c497f1dd5c5cda4cf95ab7c14d58648 AS base

EXPOSE 8080

RUN mkdir -p /srv/cloud-init
COPY ./data /srv/cloud-init
COPY ./Caddyfile /etc/caddy/Caddyfile
