FROM docker.io/library/caddy:2-alpine@sha256:ad27e531c8b286ff153c0e6e16587a1583e4111bb58c4d83bd73d6d3ef0a0ce1 AS base

EXPOSE 8080

RUN mkdir -p /srv/cloud-init
COPY ./data /srv/cloud-init
COPY ./Caddyfile /etc/caddy/Caddyfile
